게시물 왼쪽 상단에 하트 버튼 생성
prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang pull request #61
Opened 2023-09-10 14:15 UTC by jkea1

## 간단한 내용 설명
- Icon 컴포넌트 생성
- IconButton 컴포넌트 생성 

## 궁금한 점
- 중복되는 type이 있어 type 폴더가 따로 있어야 할 것 같음.
- IconSet 파일에 우선 svg를 정리했는데 다른 좋은 방법이 있으면 알려주세요.

2023-09-10 14:56 UTC, backward99 reviewed
저도 빨리 공부하고 생성하고 해야겠네요...! 수고하셨습니다!

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +import { Icon } from '../Icon';
현재 폴더가 아니라면 ~로 사용하는 것도 좋을 것 같습니다!

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +      className={`${className} ${defaultStyle}`}
props로 받아온 className을 defaultStyle보다 나중에 적지 않아도 되나요? className으로 받아온 값이 defaultStyle로 덮어 써지지는 않을까 하고 생각해 봤습니다!

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +  handleOnClick?: () => void;
onClick이라는게 `React.ButtonHTMLAttributes<HTMLButtonElement>` 타입 안에 존재 하는 것 같다고 생각합니다!

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +    >
`React.ButtonHTMLAttributes<HTMLButtonElement>`타입을 확장했는데 아직 적용되지 않는 것 같습니다! `...props`를 활용해보는 것도 좋을 것 같습니다!
`event.preventDefault();`를 여기에서 사용한 이유는 handleOnclick안에 사용되어 있지 않은 걸 가정한 건가요?

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +    'inline-block w-auto rounded-full border-4 border-black bg-white p-2';
저도 이런식으로 해야겠습니다..!

2023-09-10 14:56 UTC, backward99 commented on src/components/Buttons/IconButton.tsx
> +  name,
html기본 속성에도 name이 있을 수 있으니 iconName은 어떨까요?

2023-09-10 15:38 UTC, jgjgill requested changes
작업 내용 확인했습니다..! 변경해야할 부분들이랑 궁금한 사항이 있어서 재요청드려요!

컴포넌트와 같은 작업은 보는 입장에서 스크린샷이나 영상이 있으면 더 좋을 것 같아요..!
이제부터 pr이 많아질 것 같아서 저도 스크린샷이나 영상을 남겨볼게요!! 혹은 chromatic로 스토리북으로 배포를 시키는 방향으로 나중에 이야기해도 괜찮을 것 같아요!

주석은 반드시 필요한 경우가 아니면 안써도 괜찮을 것 같아요!
제거해야 하는 주석이면 해야하는 작업이 늘어나기도 해서 힘들 것 같네요.

> 중복되는 type이 있어 type 폴더가 따로 있어야 할 것 같음.
> IconSet 파일에 우선 svg를 정리했는데 다른 좋은 방법이 있으면 알려주세요.

이 부분과 관련해서는 저는 진경님이 해당 컴포넌트를 만들 때 참고한 자료를 같이 알고 싶네요!
IconSet?을 참고한 자료에서는 어떻게 컴포넌트와 파일을 구성했는지 알아야 할 것 같아요..!

지금 구조에서는 타입같은 경우 `IconSet` 컴포넌트에서만 `export`하고 사용하는 쪽에서 불러오는 방식이 될 것 같네요.

그리고 해당 작업을 하면서 `svg`를 어떻게 사용하는지 알아야할 것 같은데 이 부분도 학습하시고 위키에 공유하면 좋겠다는 생각이 들었습니다..! 🙇‍♂️

2023-09-10 15:38 UTC, jgjgill commented on src/components/Buttons/IconButton.tsx
> +  handleOnClick?: () => void;
`handleOnClick`이라는 네이밍도 어색하게 느껴지는 것 같아요..!
`handleClick`이 저한테는 더 자연스러워서 스크럼 때 한 번 이야기 나눠보고 wiki에 추가해봐요!! 🧐

2023-09-10 15:38 UTC, jgjgill commented on src/components/Buttons/IconButton.tsx
> +        handleOnClick && handleOnClick();
강의 기반 코드인 것 같아요!!
제 생각에는 해당 부분에서 `event. preventDefault()`는 사용할 이유가 없을 것 같아요! 🤔

2023-09-10 15:38 UTC, jgjgill commented on src/components/Buttons/IconButton.tsx
> +type iconName = 'heart' | 'search'; //중복되어 사용되어 type을 정리 할 수 있는 폴더가 필요해 보임
타입에 대한 네이밍은 보통 첫글자가 대문자인 것 같더라구요!
저희도 통일시키면 좋을 것 같아요! (스크럼 때 이야기하고 위키에 추가하기!)

2023-09-10 15:38 UTC, jgjgill commented on src/components/Icon/Icon.stories.tsx
> +      </div>
스타일 코드를 어떠한 이유로 추가했는지 알 수 있을까요?
스토리북에서 확인했을 때 오히려 제한을 시키는게 아닌가라는 생각이 들어서요!!

https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/assets/79239852/01682d3e-5670-4529-9115-4e6873650daa

2023-09-11 03:12 UTC, jkea1 commented on src/components/Icon/Icon.stories.tsx
> +      </div>
디자인이 나오면 필요한 크기만  s m l 로 만들거 같아서 우선 range 방식 썼습니다.

2023-09-11 03:16 UTC, jkea1 commented
https://github.com/dnd-side-project/dnd-8th-1-frontend/tree/75642ed9384432a2b9b7d7c50eea1ef35ccebb73/src/components/base/Icon

이분이 icon 정리하는 방식이 깔끔해 보이더라구요. 링크 첨부합니다!

2023-09-11 03:44 UTC, jgjgill commented
넵..! 확인했습니다!
저희 코드도 깔끔하게 구성하면서 사용할 수 있을 것 같야요!
달라지는 부분은 타입에 대한 폴더일 것 같은데요!
저희가 여태 해온 방식이면 지금 제 생각에 타입과 관련된  파일들이 `Icon`폴더 내에 있을 것 같네요.

2023-09-11 03:45 UTC, jgjgill commented on src/components/Icon/IconSet.tsx
`ts`로 확장자명이 변경될 것 같네요!

2023-09-11 04:17 UTC, jkea1 commented
오 icon 관련 타입파일이 icon 폴더 안에 있으면 되겠군요! 네! 좋은 것 같습니다! 제가 한번 정리 해보겠습니다!! 코드도 규칙 보면서 좀 더 다듬어서 올릴게요!

2023-09-11 12:52 UTC, HongGunWoo approved these changes
너무 고생하셨습니다! 아이콘 버튼 컴포넌트는 이제 든든하겠네요 ㅎㅎ

2023-09-13 02:39 UTC, jgjgill approved these changes

2023-09-13 04:57 UTC, hyoribogo approved these changes
승인입니당~

2023-09-13 05:59 UTC, merged